### ISSUE TITLE
Cant refresh to see match

### ISSUE THREAD

**Issue by shareniece** [karnwatcharasupat/NTU-StarsExchange#7]
There is a line saying "Click me to see who matched with you!". However, when i place my cursor there, the page dosent refresh and does not even re-direct me to a new page. I cant even click on the whole sentence.

**Comment by kwatcharasupat** [comment]
Hi I'm working on it now. There will now be card to show if you have no match. Please note that the app is designed so that the whole page will not visually reload. 

I will try to add some animation to make it a bit more clear visually!
